// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/7/2026, 1:40:26 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/LEGION/Downloads/New folder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/LEGION/Downloads/New folder/components/dashboard/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/LEGION/Downloads/New folder/components/ui/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/LEGION/Downloads/New folder/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/LEGION/Downloads/New folder/plugins/**/*.{js,ts,mjs}","C:/Users/LEGION/Downloads/New folder/composables/**/*.{js,ts,mjs}","C:/Users/LEGION/Downloads/New folder/utils/**/*.{js,ts,mjs}","C:/Users/LEGION/Downloads/New folder/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/LEGION/Downloads/New folder/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/LEGION/Downloads/New folder/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/LEGION/Downloads/New folder/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;